apiVersion: v1
kind: Service
metadata:
  name: {{ include "kmorph.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kmorph.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "kmorph.selectorLabels" . | nindent 4 }}
